customCommands:
  - key: "<c-a>"
    context: "commits"
    description: "Set commiter date to author date"
    prompts:
      - type: "confirm"
        key: "Confirm"
        title: "Set commiter date to author date"
        body: "Are you sure you want to update the commiter date?"
    command: "git rebase --autostash --keep-empty --no-autosquash --rebase-merges --committer-date-is-author-date {{.SelectedCommit.Hash}}^"
