import = ["/home/juan/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font"

[shell]
args = [
  "-c",
  "tmux -q has-session && exec tmux attach-session || exec tmux new-session"
]
program = "/bin/sh"
