#!/bin/sh

cd ~

# User preferences
export SHELL=fish
export EDITOR=nvim
export PAGER=less
export BROWSER=firefox

# ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
# export XCURSOR_THEME=Bibata-Modern-Classic

# Set a cursor size
# export XCURSOR_SIZE=24

exec Hyprland